### ISSUE TITLE
Don't make it remove line breaks

### ISSUE THREAD

**Issue by alexdd55** [TheFlow95/DecodeHTML.swift#1]
Is there a way to not remove line breaks?

**Comment by flowbe** [comment]
Hello,
Do you mean that `<br>` doesn't work ?

**Comment by alexdd55** [comment]
It takes Out \n, but i would like to keep it

**Comment by flowbe** [comment]
I don't think it's possible because the input string has to be HTML and line breaks are not interpreted in HTML.
You can try something like that:

```
let string = "my\nstring"
let decodedString = string.stringByReplacingOccurrencesOfString("\n", withString: "<br>", options: nil, range: nil).htmlToString
```

**Comment by alexdd55** [comment]
Easy solution. Works! Thanks a lot :)

**Comment by flowbe** [comment]
You're welcome :)
